finalproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('moviessapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

moviessapp/urls.py
from django.urls import path
from . import views
app_name='moviessapp'
urlpatterns = [
    path('search/',views.searchresult,name='searchresult'),
    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('movie/<int:id>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('logout/',views.logout,name='logout'),
    path('category_movies/<int:category_id>/', views.category_movies, name='category_movies'),
    path('userprofile/',views.userprofile,name='userprofile'),
    path('updateprofile/',views.updateprofile,name='updateprofile'),
    path('deleteprofile/',views.deleteprofile,name='deleteprofile'),
    path('deletemovie/<int:movie_id>/', views.deletemovie, name='deletemovie'),
    path('addcategory/', views.addcategory, name='addcategory'),
    path('updatemovie//<int:id>/',views.updatemovie,name='updatemovie')


]

templates/addcategory.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Add CATEGORY
{% endblock %}
{% block title %}
    ADD NEW category
{% endblock %}
{% block content %}
<form method="POST" style="margin-top: 40px;">
        {% csrf_token %}
        <label for="category_name">Category Name:</label>
        <input type="text" id="category_name" name="category_name" required>

        <button type="submit">Add Category</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title%} {% endblock %}</title>
</head>
<body>
<div class="container">
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock %}
</div>
<script src="https://kit.fontawesome.com/4619f7735b.js" ></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/category_movies.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Review and manage items in your shopping cart.
{% endblock %}
{% block title %}
    category Based Movies
{% endblock %}
{% block content %}
<h2>{{ category.name }}-Movies</h2>
    <div class="container">
     <div class="row">
        {% for movie in movies %}
            <div class="col-md-4 mb-5">
             <div class="card" style="width: 18rem;margin-top: 40px; ">
                 <img class="card-img-top" src="{{movie.poster.url}}" alt=""  height="150px">
  <div class="card-body">
      <h3 class="card-title">{{movie.title}}</h3>
      <p class="card-text">{{movie.category}}</p>
      <p class="card-text">{{movie.release_date}}</p>
      <a href="{%url 'moviessapp:details' movie.id %}" class="btn btn-danger">click  movie </a>
  </div>
             </div>
         </div>
        {% endfor %}
     </div>
    </div>
{% endblock %}

templates/deletemovie.html
{% load static %}
{% block title %}
<h1 style="background-color: #000000; color: #ffffff;"><center> DELETE MOVIE</center></h1>
{% endblock %}
{% block content %}
<div class="container">
    <p>Are you sure you want to delete the movie?</p>
    <form method="POST">
    {% csrf_token %}
        <button type="submit">Delete </button>
</form>
</div>
{% endblock %}

templates/deleteprofile.html
{% load static %}
{% block title %}
<h1 style="background-color: #000000; color: #ffffff;"><center> DELETE PROFILE</center></h1>
{% endblock %}
{% block content %}
<div class="container">
    <p>Are you sure you want to delete your profile?</p>
    <form method="POST">
    {% csrf_token %}
        <button type="submit">Delete </button>
</form>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Review and manage items in your shopping cart.
{% endblock %}
{% block title %}
    DETAILS ABOUT MOVIE
{% endblock %}
{% block content %}
<div class="continer" xmlns="http://www.w3.org/1999/html">
    <div class="row">
             <div class="col-md-6" style="margin-top: 30px; ">
                <img src="{{films.poster.url}}" style="width: 300px; height: 225px; object-fit: cover;"  > <br>
            </div>
                <div class="col-md-5 " style="margin-top: 30px; ">
                    <b><u>{{films.title}}</u></b><br> Category -{{films.category}}<br>
                    {{films.description}} ( {{films.release_date}} )<br>
                    Actors of this movie - {{films.actors}}<br>
                    TRAILER -->  <a href="{{ films.trailer_link }}" target="_blank">{{ films.trailer_link }}</a><br>
<br>
                    <a href="{{ films.get_absolute_url }}"><button class="btn btn-danger">DELETE</button></a>
                    <a href="{%url 'moviessapp:updatemovie' films.id %}"><button class="btn btn-warning">UPDATE</button></a> <br><br>
                </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}
{% block title %}
    FILM CORNER
{% endblock %}
{% block content %}

<div class="container">
     <div class="row">
         {% for r in movie_list %}
         <div class="col-md-4 mb-5">
             <div class="card" style="width: 18rem;margin-top: 40px; ">
                 <img class="card-img-top" src="{{r.poster.url}}" alt=""  height="150px">
  <div class="card-body">
      <h3 class="card-title">{{r.title}}</h3>
      <p class="card-text">{{r.category}}</p>
      <p class="card-text">{{r.release_date}}</p>
      <a href="{%url 'moviessapp:details' r.id %}" class="btn btn-danger">click  movie </a>
  </div>
             </div>
         </div>
         {% endfor %}
     </div>
<div class="mx-auto">
        {% if movie_list.has_other_pages %}
        <hr>
        <div class="text-center">
            {% for pg in movie_list.paginator.page_range %}
            <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if movie_list.number == pg %}active{% endif %}">
                {{ pg }}
            </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
</head>
<body bgcolor="#ADD8E6">
<h2><center>LOG IN </center> </h2>
<form action="" method="post"><center>
    {% csrf_token %}
    <input type="text" name="username" placeholder="ENTER YOUR USERNAME"><br>
    <br>
    <input type="password" name="password" placeholder="ENTER YOUR PASSWORD"><br>
    <br>
    <input type="submit">
</center>
</form>
 <a href="{% url 'moviessapp:register' %}"><B>REGISTER</B></a>
{% for e in messages %}
<h2><center>{{e}}</center></h2>
{% endfor %}
</body>
</html>

templates/navbar.html
<nav class="main_nav" style="margin-top: 40px;">
  <ul class="nav justify-content-center">
    {% if user.is_authenticated %}
    <li> <b>Welcome-</b><a href="{% url 'moviessapp:userprofile' %}"><b><i class="fa-solid fa-user">&nbsp; {{user.username}} </i></b></a></li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'moviessapp:logout' %}"><b>LOG OUT</b></a>
  </li>
    {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'moviessapp:register' %}"><b>REGISTER</b></a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="{% url 'moviessapp:login' %}"><b>LOG IN</b></a>
  </li>
    {% endif %}
</ul>
</nav>


<nav class="navbar navbar-expand-lg navbar-light bg-info" style="margin-top: 40px;" data-bs-theme="dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'moviessapp:home' %}"><b>HOME</b></a>
      </li>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <b>FILMS</b>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="{% url 'moviessapp:home' %}">All Movies</a></li>
          {% for cat in category_list %}
                <li><a class="dropdown-item" href="{{ cat.get_absolute_url }}">{{ cat.name }} </a></li>
          {% endfor %}
        </ul>
      </li>
    </ul>
    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'moviessapp:add'  %}" ><button class="btn btn-primary">ADD MOVIES</button></a>
    <a class="nav-link" href="{% url 'moviessapp:addcategory'  %}" ><button class="btn btn-primary">ADD CATEGORY</button></a>
    {% endif %}
    <form class="form-inline my-3 my-lg-0" action="{% url 'moviessapp:searchresult' %}" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q"   aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
  </div>
</nav>

templates/notforupdate.html
{% load static %}
{% block title %}
<h1 style="background-color: #800000; color: #ffffff;"><center> NOT THE USER</center></h1>
{% endblock %}

{% block content %}
    <div class="container">
        <center><p>{{ message }}</p>
        <a href="{% url 'moviessapp:home' %}">Back to Home</a>
    </center></div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>REGISTER</title>
</head>
<body bgcolor="#90EE90">
<h2><center>REGISTRATION</center></h2>
<form action="" method="post"><CENTER>
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter the username"><br>
    <br>
    <input type="text" name="first_name" placeholder="enter your firstname"><br>
    <br>
    <input type="text" name="last_name" placeholder="enter your lastname"><br>
    <br>
    <input type="email" name="email" placeholder="enter your email id"><br>
    <br>
    <input type="password" name="password" placeholder="enter the password"><br>
    <br>
    <input type="password" name="password again" placeholder="confirm the password"><br>
    <br>
    <input type="submit">

</CENTER>
</form>
{% for i in messages %}
<h2>{{i}}</h2>
{% endfor %}
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Explore our search results to find relevant information and discover a wide range of topics.
    Our search page helps you quickly locate movies with their categories
    Start your search now and uncover valuable content at your fingertips
{% endblock %}
{% block title %}
    SEARCH
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_text_search">Your Search for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="col-md-4 mb-5">
             <div class="card" style="width: 18rem;margin-top: 40px; ">
                 <img class="card-img-top" src="{{movie.poster.url}}" alt=""  height="150px">
  <div class="card-body">
      <h3 class="card-title">{{movie.title}}</h3>
      <p class="card-text">{{movie.category}}</p>
      <p class="card-text">{{movie.release_date}}</p>
      <a href="{%url 'moviessapp:details' movie.id %}" class="btn btn-danger">click  movie </a>
  </div>
             </div>
         </div>
        {% empty %}
            <div class="row mx_auto">
                 <p class="text-center my_text_search">No Results Found</p>
            </div>
       {% endfor %}
     </div>
    </div>


{% endblock %}

templates/updateprofile.html
{% load static %}
{% block title %}
<h1 style="background-color: #FFA500; color: #ffffff;"><center> UPDATE PROFILE</center></h1>
{% endblock %}
{% block content %}
<div class="container ">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Profile</button>
    </form>
</div>
{% endblock %}

templates/userprofile.html
{% load static %}
{% block title %}
<h1 style="background-color: blue; color: #ffffff;"><center>USER PROFILE</center></h1>
{% endblock %}
{% block content %}
<div class="container" style="background-color: #ecf0f1; padding: 20px;">
    <div class="row" >
{% if user_details %}
        <center>
        <p>Username: {{ user_details.username }}</p>
        <p>Name:  {{ user_details.first_name }} {{ user_details.last_name }}</p>
        <p>Email: {{ user_details.email }}</p>
    {% else %}
        <p>You need to log in to view your profile.</p>
    {% endif %}
            </center>
    </div>

    <a href="{% url 'moviessapp:home' %}">HOME</a>
     &nbsp;<a href="{% url 'moviessapp:updateprofile' %}" ><button class="btn btn-warning">UPDATE</button></a>
    &nbsp;<a href="{% url 'moviessapp:deleteprofile' %}" ><button class="btn btn-danger">DELETE</button></a>
</div>
{% endblock %}